"""initial migration

Revision ID: 29680d4be6dc
Revises: 
Create Date: 2024-07-12 21:39:00.627353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29680d4be6dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_name'))
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    # ### end Alembic commands ###
