"""added notification table

Revision ID: 3272a7d05f80
Revises: 9513faaab61a
Create Date: 2024-07-24 01:12:48.954562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3272a7d05f80'
down_revision = '9513faaab61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationFacultyTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_username'], ['facultyTable.faculty_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificationStudentTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_username'], ['studentTable.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificationStudentTable')
    op.drop_table('notificationFacultyTable')
    # ### end Alembic commands ###
