"""Changes in schema added adminTable

Revision ID: 67a8238140b3
Revises: 
Create Date: 2024-10-22 16:22:11.096868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a8238140b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminTable',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('branchTable',
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('branch_code'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('facultyTable',
    sa.Column('faculty_code', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('cabin_number', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('faculty_code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('faculty_code')
    )
    op.create_table('courseTable',
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('course_instructor_code', sa.String(length=100), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['branch_code'], ['branchTable.branch_code'], ),
    sa.ForeignKeyConstraint(['course_instructor_code'], ['facultyTable.faculty_code'], ),
    sa.PrimaryKeyConstraint('course_code'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('notificationFacultyTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_username'], ['facultyTable.faculty_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentTable',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('year_of_joining', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['branch_code'], ['branchTable.branch_code'], ),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendanceTable',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('attendance', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courseTable.course_code'], ),
    sa.ForeignKeyConstraint(['username'], ['studentTable.username'], ),
    sa.PrimaryKeyConstraint('username', 'course_code', 'date')
    )
    op.create_table('marksTable',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('ExamType', sa.String(length=50), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courseTable.course_code'], ),
    sa.ForeignKeyConstraint(['username'], ['studentTable.username'], ),
    sa.PrimaryKeyConstraint('username', 'course_code', 'ExamType')
    )
    op.create_table('notificationStudentTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_username'], ['studentTable.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_courses',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courseTable.course_code'], ),
    sa.ForeignKeyConstraint(['username'], ['studentTable.username'], ),
    sa.PrimaryKeyConstraint('username', 'course_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses')
    op.drop_table('notificationStudentTable')
    op.drop_table('marksTable')
    op.drop_table('attendanceTable')
    op.drop_table('studentTable')
    op.drop_table('notificationFacultyTable')
    op.drop_table('courseTable')
    op.drop_table('facultyTable')
    op.drop_table('branchTable')
    op.drop_table('adminTable')
    # ### end Alembic commands ###
