"""final table

Revision ID: 9513faaab61a
Revises: 9f5d1bd24d8f
Create Date: 2024-07-23 11:29:00.887761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9513faaab61a'
down_revision = '9f5d1bd24d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminTable', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('id')

    with op.batch_alter_table('attendanceTable', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('branchTable', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('courseTable', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('facultyTable', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('marksTable', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('studentTable', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studentTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))

    with op.batch_alter_table('marksTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))

    with op.batch_alter_table('facultyTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))

    with op.batch_alter_table('courseTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))

    with op.batch_alter_table('branchTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))

    with op.batch_alter_table('attendanceTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))

    with op.batch_alter_table('adminTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
